"""
Build each product's GitHub repo contents from its readable source.

  products_src/<product>/**/*.lua        (readable code you edit - never pushed)
        |  Prometheus obfuscation (LuaJIT) + compile check
        v
  repos/<repo>/**/*.lua                  (push this folder to github.com/<owner>/<repo>)
  repos/<repo>/manifest.lua              (file list the launcher downloads)

Run:
  python tools/build_plugins.py                       # all products, Bot preset
  python tools/build_plugins.py sp_pull               # one product
  python tools/build_plugins.py --preset Minify       # Bot | Minify | Weak | Medium | Strong
  python tools/build_plugins.py --no-obfuscate        # plain copy, for debugging
"""
import argparse
import os
import shutil
import subprocess
import sys
import zlib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "products_src"
REPOS = ROOT / "repos"
PROMETHEUS = ROOT / "tools" / "prometheus"
BOT_CONFIG = ROOT / "tools" / "obfuscate_bot.lua"

# product folder -> output repo folder (= GitHub repo name). Folders listed in
# `skip` (and any dot-folder) are never shipped.
PRODUCTS = {
    "mf_route_tool": {"repo": "mf-route-tool", "skip": set()},
    "sp_pull": {"repo": "sp-pull", "skip": {"Source"}},
}

README = """# {repo}

Build output for the **Master Farmer** launcher - do not edit by hand.
The files are obfuscated; the readable source is not published.

Loaded in game by the Master Farmer launcher (Sylvanas), which reads
`manifest.lua` and downloads every listed file into memory.
"""


def find_luajit():
    found = shutil.which("luajit")
    if found:
        return found
    default = Path(os.environ.get("LOCALAPPDATA", "")) / "Programs" / "LuaJIT" / "bin" / "luajit.exe"
    if default.exists():
        return str(default)
    sys.exit("LuaJIT not found. Install it with:  winget install DEVCOM.LuaJIT")


def run(cmd, **kw):
    return subprocess.run(cmd, capture_output=True, text=True, stdin=subprocess.DEVNULL, **kw)


def obfuscate(luajit, preset, src, dst):
    dst.parent.mkdir(parents=True, exist_ok=True)
    cfg = ["--config", str(BOT_CONFIG)] if preset == "Bot" else ["--preset", preset]
    result = run([luajit, "cli.lua", *cfg, str(src), "--out", str(dst)], cwd=PROMETHEUS)
    if result.returncode != 0 or not dst.exists():
        sys.exit(f"Prometheus failed on {src}:\n{result.stdout}\n{result.stderr}")


def compile_check(luajit, path):
    result = run([luajit, "-e", f"local f, e = loadfile([==[{path}]==]); if not f then io.stderr:write(e) os.exit(1) end"])
    if result.returncode != 0:
        sys.exit(f"Compile check failed for {path}: {result.stderr}")


def lua_files(prod_dir, skip):
    for src in sorted(prod_dir.rglob("*.lua")):
        parts = src.relative_to(prod_dir).parts
        if any(p.startswith(".") or p in skip for p in parts[:-1]):
            continue
        yield src


def write_manifest(out_dir, files):
    rows, total = [], 0
    for rel in files:
        data = (out_dir / rel).read_bytes().replace(b"\r\n", b"\n")
        total += len(data)
        rows.append(f'        {{ path = "{rel}", hash = "{zlib.adler32(data):08x}", size = {len(data)} }},')
    (out_dir / "manifest.lua").write_text(
        "-- Generated by tools/build_plugins.py - do not edit by hand.\n"
        "return {\n"
        f"    count = {len(files)},\n    bytes = {total},\n    files = {{\n"
        + "\n".join(rows) + "\n    },\n}\n",
        encoding="utf-8",
    )
    return total


LAUNCHER_SRC = ROOT / "plugin" / "Master_Farmer"
LAUNCHER_OUT = ROOT / "dist" / "Master_Farmer"


def build_launcher(luajit, preset):
    """Encoded copy of the launcher plugin for public distribution.
    The readable source in plugin/Master_Farmer is never published."""
    if LAUNCHER_OUT.exists():
        shutil.rmtree(LAUNCHER_OUT)
    n = 0
    for src in sorted(LAUNCHER_SRC.rglob("*.lua")):
        dst = LAUNCHER_OUT / src.relative_to(LAUNCHER_SRC)
        obfuscate(luajit, preset, src, dst)
        compile_check(luajit, dst)
        n += 1
    print(f"  launcher         -> dist/Master_Farmer     {n:3d} files  (Prometheus {preset})")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("products", nargs="*", help="product folder names (default: all)")
    ap.add_argument("--preset", default="Bot", choices=["Bot", "Minify", "Weak", "Medium", "Strong"])
    ap.add_argument("--no-obfuscate", action="store_true")
    ap.add_argument("--launcher", action="store_true",
                    help="build the encoded launcher into dist/Master_Farmer instead of products")
    args = ap.parse_args()

    luajit = find_luajit()
    if not args.no_obfuscate and not (PROMETHEUS / "cli.lua").exists():
        sys.exit("Prometheus missing. Run:  git clone https://github.com/prometheus-lua/Prometheus.git tools/prometheus")

    if args.launcher:
        build_launcher(luajit, args.preset)
        return

    names = args.products or list(PRODUCTS)
    mode = "plain copy" if args.no_obfuscate else f"Prometheus {args.preset}"
    for name in names:
        if name not in PRODUCTS:
            sys.exit(f"Unknown product '{name}'. Known: {', '.join(PRODUCTS)}")
        spec, prod_dir = PRODUCTS[name], SRC / name
        if not (prod_dir / "main.lua").exists():
            sys.exit(f"{prod_dir} has no main.lua")
        out = REPOS / spec["repo"]
        out.mkdir(parents=True, exist_ok=True)
        # Clear old build output but keep the repo's .git folder
        for child in out.iterdir():
            if child.name != ".git":
                shutil.rmtree(child) if child.is_dir() else child.unlink()

        files = []
        for src in lua_files(prod_dir, spec["skip"]):
            rel = src.relative_to(prod_dir).as_posix()
            dst = out / rel
            if args.no_obfuscate:
                dst.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(src, dst)
            else:
                obfuscate(luajit, args.preset, src, dst)
            compile_check(luajit, dst)
            files.append(rel)
        total = write_manifest(out, files)
        (out / "README.md").write_text(README.format(repo=spec["repo"]), encoding="utf-8")
        print(f"  {name:16s} -> repos/{spec['repo']:16s} {len(files):3d} files  {total // 1024} KB  ({mode})")


if __name__ == "__main__":
    main()
